program PascalCoin_wallet_classic;

{$IFDEF FPC}
  {$MODE Delphi}
{$ENDIF}

uses
  {$IFnDEF FPC}
  {$ELSE}
  {$IFDEF LINUX}
  cthreads,
  {$ENDIF }
  Interfaces,
  {$ENDIF }
  Forms,
  UBlockChain in 'core\UBlockChain.pas',
  UCrypto in 'core\UCrypto.pas',
  UTime in 'core\UTime.pas',
  UWallet in 'core\UWallet.pas',
  UOpTransaction in 'core\UOpTransaction.pas',
  UAccounts in 'core\UAccounts.pas',
  UConst in 'core\UConst.pas',
  UThread in 'core\UThread.pas',
  ULog in 'core\ULog.pas',
  UNode in 'core\UNode.pas',
  UECIES in 'core\UECIES.pas',
  UAES in 'core\UAES.pas',
  UFRMWallet in 'gui-classic\UFRMWallet.pas' {FRMWallet},
  UFileStorage in 'core\UFileStorage.pas',
  UFRMPascalCoinWalletConfig in 'gui-classic\UFRMPascalCoinWalletConfig.pas' {FRMPascalCoinWalletConfig},
  UFRMAbout in 'gui-classic\UFRMAbout.pas' {FRMAbout},
  UFRMOperation in 'gui-classic\UFRMOperation.pas' {FRMOperation},
  UFRMWalletKeys in 'gui-classic\UFRMWalletKeys.pas' {FRMWalletKeys},
  UFRMNewPrivateKeyType in 'gui-classic\UFRMNewPrivateKeyType.pas' {FRMNewPrivateKeyType},
  UFRMPayloadDecoder in 'gui-classic\UFRMPayloadDecoder.pas' {FRMPayloadDecoder},
  UFRMNodesIp in 'gui-classic\UFRMNodesIp.pas' {FRMNodesIp},
  UTCPIP in 'core\UTCPIP.pas',
  URPC in 'core\URPC.pas',
  UPoolMining in 'core\UPoolMining.pas',
  UOpenSSL in 'core\UOpenSSL.pas',
  UOpenSSLdef in 'core\UOpenSSLdef.pas',
  UBaseTypes in 'core\UBaseTypes.pas',
  UAccountKeyStorage in 'core\UAccountKeyStorage.pas',
  UTxMultiOperation in 'core\UTxMultiOperation.pas',
  USettings in 'core\USettings.pas',
  UAppParams in 'libraries\pascalcoin\UAppParams.pas',
  UFolderHelper in 'libraries\pascalcoin\UFolderHelper.pas',
  UJSONFunctions in 'libraries\pascalcoin\UJSONFunctions.pas',
  blcksock in 'libraries\synapse\blcksock.pas',
  synafpc in 'libraries\synapse\synafpc.pas',
  synsock in 'libraries\synapse\synsock.pas',
  synautil in 'libraries\synapse\synautil.pas',
  synacode in 'libraries\synapse\synacode.pas',
  synaip in 'libraries\synapse\synaip.pas',
  UChunk in 'core\UChunk.pas',
  UGridUtils in 'gui-classic\UGridUtils.pas',
  UFRMMemoText in 'gui-classic\UFRMMemoText.pas' {FRMMemoText},
  UFRMAccountSelect in 'gui-classic\UFRMAccountSelect.pas' {FRMAccountSelect},
  UFRMRPCCalls in 'gui-classic\UFRMRPCCalls.pas' {FRMRPCCalls},
  httpsend in 'libraries\synapse\httpsend.pas',
  UFRMOperationsExplorer in 'gui-classic\UFRMOperationsExplorer.pas' {FRMOperationsExplorer},
  UFRMRandomOperations in 'gui-classic\UFRMRandomOperations.pas' {FRMRandomOperations},
  UNetProtocol in 'core\NetProtocol\UNetProtocol.pas',
  UNetProtocolConst in 'core\NetProtocol\UNetProtocolConst.pas',
  UNetworkAdjustedTime in 'core\NetProtocol\UNetworkAdjustedTime.pas',
  UNetData in 'core\NetProtocol\UNetData.pas',
  UNetConnection in 'core\NetProtocol\UNetConnection.pas',
  UNodeServerAddress in 'core\NetProtocol\UNodeServerAddress.pas',
  UOrderedServerAddressListTS in 'core\NetProtocol\UOrderedServerAddressListTS.pas',
  UNetStatistics in 'core\NetProtocol\UNetStatistics.pas',
  UNetServer in 'core\NetProtocol\UNetServer.pas',
  UNetClient in 'core\NetProtocol\UNetClient.pas',
  UThreadGetNewBlockChainFromClient in 'core\NetProtocol\UThreadGetNewBlockChainFromClient.pas',
  UNetDataNotifyEventsThread in 'core\NetProtocol\UNetDataNotifyEventsThread.pas',
  UNetClientsDestroyThread in 'core\NetProtocol\UNetClientsDestroyThread.pas',
  UThreadCheckConnections in 'core\NetProtocol\UThreadCheckConnections.pas',
  UThreadDiscoverConnection in 'core\NetProtocol\UThreadDiscoverConnection.pas',
  UNetClientThread in 'core\NetProtocol\UNetClientThread.pas',
  UNetServerClient in 'core\NetProtocol\UNetServerClient.pas',
  UOperationBlock in 'core\Accounts\UOperationBlock.pas',
  UAccountKey in 'core\Accounts\UAccountKey.pas',
  URawBytes in 'core\BaseTypes\URawBytes.pas',
  UTickCount in 'core\BaseTypes\UTickCount.pas',
  UOrderedRawList in 'core\Lists\UOrderedRawList.pas',
  UOperationsHashTree in 'core\Lists\UOperationsHashTree.pas',
  UPCOperation in 'core\BlockChain\UPCOperation.pas',
  UOperationResume in 'core\BlockChain\UOperationResume.pas',
  UMultiOpSender in 'core\BlockChain\UMultiOpSender.pas',
  UMultiOpReceiver in 'core\BlockChain\UMultiOpReceiver.pas',
  UMultiOpChangeInfo in 'core\BlockChain\UMultiOpChangeInfo.pas',
  UOpChangeAccountInfoType in 'core\BlockChain\UOpChangeAccountInfoType.pas',
  UAccountPreviousBlockInfo in 'core\Accounts\UAccountPreviousBlockInfo.pas',
  UAccountPreviousBlockInfoData in 'core\Accounts\UAccountPreviousBlockInfoData.pas',
  UPCSafeBoxTransaction in 'core\Accounts\UPCSafeBoxTransaction.pas',
  UOrderedAccountList in 'core\Lists\UOrderedAccountList.pas',
  UAccount in 'core\Accounts\UAccount.pas',
  UAccountInfo in 'core\Accounts\UAccountInfo.pas',
  UAccountState in 'core\Accounts\UAccountState.pas',
  UPCSafeBox in 'core\Accounts\UPCSafeBox.pas',
  UOrderedBlockAccountList in 'core\Lists\UOrderedBlockAccountList.pas',
  UBlockAccount in 'core\Accounts\UBlockAccount.pas',
  UMemBlockAccount in 'core\Accounts\UMemBlockAccount.pas',
  UMemOperationBlock in 'core\Accounts\UMemOperationBlock.pas',
  UDynRawBytes in 'core\BaseTypes\UDynRawBytes.pas',
  U32Bytes in 'core\BaseTypes\U32Bytes.pas',
  UMemAccount in 'core\Accounts\UMemAccount.pas',
  UAccountInfoKS in 'core\Accounts\UAccountInfoKS.pas',
  UAccountUpdateStyle in 'core\Accounts\UAccountUpdateStyle.pas',
  UPCSafeBoxHeader in 'core\Accounts\UPCSafeBoxHeader.pas',
  UPBlockAccount in 'core\Accounts\UPBlockAccount.pas',
  UOrderedAccountKeysList in 'core\Lists\UOrderedAccountKeysList.pas',
  UBaseType in 'core\BaseTypes\UBaseType.pas',
  U256RawBytes in 'core\BaseTypes\U256RawBytes.pas',
  UPlatform in 'core\BaseTypes\UPlatform.pas',
  UAccountComp in 'core\Accounts\UAccountComp.pas',
  UStreamOp in 'core\Accounts\UStreamOp.pas',
  UPascalCoinProtocol in 'core\Accounts\UPascalCoinProtocol.pas',
  UBigNum in 'core\Crypto\UBigNum.pas',
  UOrderedCardinalList in 'core\Lists\UOrderedCardinalList.pas',
  UCardinalsArray in 'core\Accounts\UCardinalsArray.pas',
  UAccountKeyArray in 'core\Accounts\UAccountKeyArray.pas',
  UPCOperationClass in 'core\BlockChain\UPCOperationClass.pas',
  UPCOperationsComp in 'core\BlockChain\UPCOperationsComp.pas',
  UPtrInt in 'core\BaseTypes\UPtrInt.pas',
  UThreadID in 'core\BaseTypes\UThreadID.pas',
  UPtrUInt in 'core\BaseTypes\UPtrUInt.pas',
  UPCBank in 'core\BlockChain\UPCBank.pas',
  UStorage in 'core\BlockChain\UStorage.pas',
  UOrphan in 'core\BlockChain\UOrphan.pas',
  UPCBankLog in 'core\BlockChain\UPCBankLog.pas',
  UStorageClass in 'core\BlockChain\UStorageClass.pas',
  UPCBankNotify in 'core\BlockChain\UPCBankNotify.pas',
  UNetProtocolVersion in 'core\NetProtocol\Types\UNetProtocolVersion.pas',
  UNetHeaderData in 'core\NetProtocol\Types\UNetHeaderData.pas',
  UNetTransferType in 'core\NetProtocol\Types\UNetTransferType.pas',
  UNetMessage_Hello in 'core\NetProtocol\Types\UNetMessage_Hello.pas',
  UNetRequestRegistered in 'core\NetProtocol\Types\UNetRequestRegistered.pas',
  UProcessReservedAreaMessage in 'core\NetProtocol\UProcessReservedAreaMessage.pas',
  UECPrivateKey in 'core\Crypto\UECPrivateKey.pas',
  UECDSA_Public in 'core\Crypto\UECDSA_Public.pas',
  UCryptoException in 'core\Crypto\UCryptoException.pas';

{$R *.res}

begin
  Application.Initialize;
  {$IFDEF WINDOWS}Application.MainFormOnTaskbar := True;{$ENDIF}
  Application.Title := 'Pascal Coin Wallet, Miner & Explorer';
  Application.CreateForm(TFRMWallet, FRMWallet);
  Application.Run;
end.
